info:
  app:
    name: saas-control-plane
    description: SaaS Control Plane
    version: 1.0
server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-alias: selfsigned
    key-store-type: PKCS12
    key-store-password: password
  # Enable response compression
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  # Enable HTTP/2 support, if the current environment supports it
  http2:
    enabled: true

security:
  jwt:
    token-validity-in-seconds: 6060
  cors:
    #Remove if you do not need to enable cors.
    allowed-origins:
      - "http://localhost:4200"
      - "http://127.0.0.1:8080"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization,Link,X-Total-Count"
    allow-credentials: true
    max-age: 1800
logging:
  level:
    org:
      springframework:
        web: DEBUG


http-server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

aws:
  vpc: XXXXX
  command: uname -a
  ec2-security-group: XXXXX
  key-pair-name: XXXXX


spring:
  application:
    name: saas-control-plane
  main:
    #Avoid DataSource issue #1142 overriding bean definition
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:~/saas
    username: sa
    password:
    driver-class-name: org.h2.Driver
    max-active: 10
    max-idle: 8
    max-wait: 10000
    min-evictable-idle-time-millis: 1000
    min-idle: 8
    time-between-eviction-runs-millis: 1
  jpa:
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
  resources:
    cache:
      cachecontrol:
        # Maximum time the response should be cached (in seconds)
        max-age: 120
        # The cache must re-validate stale resources with the server. Any expired resources must not be used without re-validating.
        must-revalidate: true

  h2:
    console:
      enabled: true
      path: /h2

  cache:
    jcache:
      config: classpath:ehcache.xml
